---

- name: Prepare OS for management
  ansible.builtin.include_tasks: prepare.yml

- name: Import package list from older variable packages
  ansible.builtin.set_fact:
    __package_list: "{{ package_list | default(packages) | default([]) }}"

- name: Show package list
  ansible.builtin.debug:
    msg: "{{ __package_list }}"

- name: Define task list
  ansible.builtin.set_fact:
    package_tasklist: "{{ 'pip' if package_mgr == 'pip' else 'packages' }}-{{ package_mode }}.yml"
    package_tasklist1: "{{ role_path }}/tasks/{{ 'pip' if package_mgr == 'pip' else 'packages' }}-{{ package_mode }}.yml"

- name: Including task list {{ package_tasklist }}
  ansible.builtin.include_tasks: "{{ package_tasklist1 }}"
