---

- name: Import package list from older variable packages
  set_fact:
    package_list: "{{ package_list | default(packages) | default([]) }}"

- name: Define task list 
  set_fact:
    package_tasklist: "{{ 'pip' if package_mgr == 'pip' else 'packages' }}-{{ package_mode }}.yml"
    package_tasklist1: "{{ role_path }}/tasks/{{ 'pip' if package_mgr == 'pip' else 'packages' }}-{{ package_mode }}.yml"

- name: Including task list {{ package_tasklist }}
  include_tasks: "{{ package_tasklist1 }}"
