---

- name: Updating {{ package_mgr }} package list
  include_tasks: "packages/{{ package_mgr }}-update.yml"

- name: Including task for package manager {{ package_mgr }}
  include_tasks: "packages/{{ package_mgr }}-{{ package_mode }}.yml"
