---

- name: Updating {{ package_mgr }} package list  # noqa name[template]
  ansible.builtin.include_tasks: "packages/{{ package_mgr }}-update.yml"
  when: package_update | bool

- name: Including task for package manager {{ package_mgr }}
  ansible.builtin.include_tasks: "packages/{{ package_mgr }}-{{ package_mode }}.yml"
