---

- name: Updating {{ package_mgr }} package list
  include: "packages/{{ package_mgr }}-update.yml"

- name: Including task for package manager {{ package_mgr }}
  include: "packages/{{ package_mgr }}-install.yml"

- name: Show packaged installed and/or updated
  debug:
    var: packages_result.results
  when: packages_result.results|length > 0
