---

- name: Reset package mode
  set_fact:
    _package_mode: "{{ package_mode | regex_replace('-verbose') }}"

- name: Get list of installed pip packages (pre)
  pip_package_info:
    clients: "{{ package_pip_cmd }}"
  register: pip_packages

- name: Save the package info in simplified form (pre)
  set_fact:
    package_pre: "{{ pip_packages['packages'][package_pip_cmd] }}"
    package_pre1: "{{ pip_packages['packages'][package_pip_cmd] | json_query(q1) }}"
    package_pre2: "{{ pip_packages['packages'][package_pip_cmd] | json_query(q2) }}"
  vars:
    q1: '*[].name'
    q2: '*[].{ name: name, version: version}'

- name: Including task for package manager {{ package_mgr }}
  include_tasks: "packages/{{ package_mgr }}-{{ _package_mode }}.yml"

- block:

    - name: Get list of installed pip packages (post)
      pip_package_info:
        clients: "{{ package_pip_cmd }}"
      register: pip_packages

    - name: Save the package info in simplified form (post)
      set_fact:
        package_post: "{{ pip_packages['packages'][package_pip_cmd] }}"
        package_post1: "{{ pip_packages['packages'][package_pip_cmd] | json_query(q1) }}"
        package_post2: "{{ pip_packages['packages'][package_pip_cmd] | json_query(q2) }}"
      vars:
        q1: '*[].name'
        q2: '*[].{ name: name, version: version}'

    - name: Create lists of installed/remove/changed packages
      set_fact:
        _installed: "{{ package_post1 | difference(package_pre1) | sort }}"
        _removed: "{{ package_pre1 | difference(package_post1) | sort }}"
        _updated: >
          [
            {% for item in (package_pre1 | intersect(package_post1)) -%}
            {% if (package_pre[item]|json_query('[].version')|first) != (package_post[item]|json_query('[].version')|first) %}
            "{{ item }}"{% if not loop.last %},{% endif %}
            {% endif %}
            {% endfor %}
          ]

    - name: Packages installed
      debug:
        msg: "{{ _installed }}"
      when: _installed|length > 0

    - name: Packages removed
      debug:
        msg: "{{ _removed }}"
      when: _removed|length > 0

    - name: Packages upgraded
      debug:
        msg: "{{ _updated }}"
      when: _updated|length > 0

  when: pip_packages_result.changed
