---

- name: Converge
  hosts: all
  vars:
    packages_add:
      - rsync
      - curl
    packages_rm:
      - patch
  tasks:

    - name: 'ansible-role-package / install'
      include_role:
        name: ansible-role-package
      vars:
        package_mode: install
        package_list: "{{ packages_add }}"

    - name: 'ansible-role-package / remove'
      include_role:
        name: ansible-role-package
      vars:
        package_mode: remove
        package_list: "{{ packages_rm }}"

    - name: 'ansible-role-package / update'
      include_role:
        name: ansible-role-package
      vars:
        package_mode: upgrade-verbose
