---

- name: Converge
  hosts: all
  vars:
    packages_add:
      - rsync
      - zip
    packages_rm:
      - jq
    # pip_site_upgrade: True
    python_virtualenv_root: /tmp/venv
    python_virtualenvs:
      - name: env1
        python: /usr/bin/python3
        site_packages: false
        packages:
          - pip
  roles:
    - deitkrachten.python
  tasks:

    # Skip Alpine on Ansible 2.9
    - name: Skip Alpine / Ansible 2.9
      meta: end_play
      when: ansible_distribution == 'Alpine' and ansible_version['full'] is search('^2.9')

    # dnf / yum / apt / apk

    - name: 'ansible-role-package / os-packages / install / non-verbose'
      include_role:
        name: ansible-role-package
        apply:
          tags: molecule-idempotence-notest
      vars:
        package_mode: install
        package_list: "{{ packages_add }}"

    - name: 'ansible-role-package / os-packages / remove / non-verbose'
      include_role:
        name: ansible-role-package
        apply:
          tags: molecule-idempotence-notest
      vars:
        package_mode: remove
        package_list: "{{ packages_rm }}"

    - name: 'ansible-role-package / os-packages / install / verbose'
      include_role:
        name: ansible-role-package
        apply:
          tags: molecule-idempotence-notest
      vars:
        package_mode: install-verbose
        package_list: "{{ packages_rm }}"

    - name: 'ansible-role-package / os-packages / update / verbose'
      include_role:
        name: ansible-role-package
      vars:
        package_mode: upgrade-verbose
        package_delay: 15
        package_retries: 2

    # pip

    - name: 'ansible-role-package / pip / install / verbose / virtualenv'
      include_role:
        name: ansible-role-package
      vars:
        package_mode: install-verbose
        package_mgr: pip
        package_pip_cmd: /tmp/venv/env1/bin/pip3
        package_list:
          - dnspython
