---

- name: Update package list (APK)
  community.general.apk:
    update_cache: true
  environment:
    HTTPS_PROXY: "{{ package_https_proxy }}"
    HTTP_PROXY: "{{ package_http_proxy }}"
    NO_PROXY: "{{ package_no_proxy }}"
    https_proxy: "{{ package_https_proxy }}"
    http_proxy: "{{ package_http_proxy }}"
    no_proxy: "{{ package_no_proxy }}"
  become: yes
  tags: molecule-idempotence-notest
  register: packages_result
  retries: "{{ package_retries | int }}"
  delay: "{{ package_delay | int }}"
  until: not packages_result.failed
