---

- name: Installing {{ description | default('additional') }} packages (APT)  # noqa name[template]
  ansible.builtin.apt:
    state: "{{ state | default('present') }}"
    name: "{{ __package_list }}"
    update_cache: "{{ update_cache | default('yes') }}"
    cache_valid_time: "{{ cache_valid_time | default(3600) }}"
    install_recommends: "{{ install_recommends | default(omit) }}"
    purge: "{{ purge | default(omit) }}"
  environment:
    HTTPS_PROXY: "{{ package_https_proxy }}"
    HTTP_PROXY: "{{ package_http_proxy }}"
    NO_PROXY: "{{ package_no_proxy }}"
    https_proxy: "{{ package_https_proxy }}"
    http_proxy: "{{ package_http_proxy }}"
    no_proxy: "{{ package_no_proxy }}"
  become: yes
  register: packages_result
  retries: "{{ package_retries | int }}"
  delay: "{{ package_delay | int }}"
  until: not packages_result.failed
