---

- name: Upgrade packages (APT)
  apt:
    force_apt_get: yes
    upgrade: yes
  become: yes
  register: packages_result

# - name: Remove dependencies that are no longer required (APT)
#   apt:
#     autoremove: yes
#   register: packages_upgrade_result2
