---

- name: Installing {{ description | default('additional') }} packages (APT)
  apt:
    state: "{{ state | default('present') }}"
    name: "{{ package_list }}"
    update_cache: "{{ update_cache | default('yes') }}"
    cache_valid_time: "{{ cache_valid_time | default(3600) }}"
    install_recommends: "{{ install_recommends | default(omit) }}"
    purge: "{{ purge | default(omit) }}"
  become: yes
  register: packages_result
