---

- name: Upgrade packages (APT)
  apt:
    force_apt_get: yes
    upgrade: yes
  register: packages_upgrade_result1

- name: Remove dependencies that are no longer required (APT)
  apt:
    autoremove: yes
  register: packages_upgrade_result2
