---

- name: Installing pip packages from pypi
  ansible.builtin.pip:
    name: "{{ __package_list }}"
    state: present
    executable: "{{ package_pip_cmd }}"
  environment:
    HTTPS_PROXY: "{{ package_https_proxy }}"
    HTTP_PROXY: "{{ package_http_proxy }}"
    NO_PROXY: "{{ package_no_proxy }}"
    https_proxy: "{{ package_https_proxy }}"
    http_proxy: "{{ package_http_proxy }}"
    no_proxy: "{{ package_no_proxy }}"
  become: yes
  register: pip_packages_result
  retries: "{{ package_retries | int }}"
  delay: "{{ package_delay | int }}"
  until: not packages_result.failed
