---

- name: Installing {{ description | default('additional') }} packages (YUM)
  yum:
    state: present
    name: "{{ packages }}"
  register: packages_result

- name: Show packaged installed and/or updated
  debug:
    var: packages_result.results
  when: packages_result.results|length > 0
