---

- name: Installing {{ description | default('additional') }} packages (Zypper)  # noqa name[template]
  community.general.zypper:
    state: present
    name: "{{ __package_list }}"
    disablerepo: "{{ package_disablerepo | default(omit) }}"
    disable_gpg_check: "{{ package_disable_gpg_check | default(disable_gpg_check) | default('no') }}"
  environment:
    HTTPS_PROXY: "{{ package_https_proxy }}"
    HTTP_PROXY: "{{ package_http_proxy }}"
    NO_PROXY: "{{ package_no_proxy }}"
    https_proxy: "{{ package_https_proxy }}"
    http_proxy: "{{ package_http_proxy }}"
    no_proxy: "{{ package_no_proxy }}"
  become: yes
  register: packages_result
  retries: "{{ package_retries | int }}"
  delay: "{{ package_delay | int }}"
  until: not packages_result.failed
